title: DAW
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Configuración de la navegación en la barra lateral
just_the_docs:
  navigation:
    - title: "Módulos"
      url: /modulos/
      children:
        - title: "Una breve descripción de los módulos"
          url: /modulos/descripcion/
