title: just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

      	url: /modulos/descripcion/

# _config.yml
nav:
  - title: "1. Home"
    path: index.md
  - title: "2. Programación"
    path: Programación.md
  - title: "3. Lenguaje de marca"
    path: LM.md
  - title: "4. Sistemas Informáticos"
    path: Sistemas.md
  - title: "5. Inglés"
    path: Inglés.md
  - title: "6. Base de dades"
    path: Bd.md

